# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

 	#61210f 	(97,33,15)
	#ea2b1f 	(234,43,31)
	#edae49 	(237,174,73)
	#f9df74 	(249,223,116)
	#f9edcc

format = """
[](#61210f)\
$os\
$username\
[](fg:#61210f bg:#ea2b1f)\
$hostname\
[](fg:#ea2b1f bg:#edae49)\
$directory\
[](fg:#edae49 bg:#f9df74)\
$git_branch\
$git_status\
[](fg:#f9df74 bg:#f9edcc)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$kotlin\
$julia\
$nodejs\
$nim\
$package\
$python\
$rust\
$scala\
[](fg:#f9edcc bg:#fff)\
$docker_context\
[ ](fg:#fff)\
"""

right_format = """
[](#33658A)\
$time\
[](#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#61210f"
style_root = "bg:#61210f"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:#ea2b1f"
ssh_symbol = "󰒋"
format = "[ $ssh_symbol $hostname ]($style)"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#61210f"
disabled = false # Disabled by default

[os.symbols]
Android = " "
NixOS = " "

[directory]
style = "bg:#edae49"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#fff"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#f9df74"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f9df74"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "󰏗 "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#f9edcc"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
