# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](plum)\
$os\
$username\
[](fg:plum bg:darkest_red)\
$hostname\
[](fg:darkest_red bg:darker_red)\
$directory\
[](fg:darker_red bg:red)\
$git_branch\
$git_status\
[](fg:red bg:orange)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$kotlin\
$julia\
$nodejs\
$nim\
$package\
$python\
$rust\
$scala\
[](fg:orange bg:yelorange)\
$docker_context\
[ ](fg:yelorange)\
"""

right_format = """
[](peach)\
$time\
[](peach)\
"""

palette = 'firenation'

[palettes.firenation]
peach = '#eba566'
yelorange = '#e67b33'
orange = '#da3c14'
red = '#cc1b07'
darker_red = '#96160b'
darkest_red = '#550f0a'
plum = '#39211c'

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:plum"
style_root = "bg:plum"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:darkest_red"
ssh_symbol = "󰒋"
format = "[ $ssh_symbol $hostname ]($style)"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:plum"
disabled = false # Disabled by default

[os.symbols]
Android = " "
NixOS = " "

[directory]
style = "bg:darker_red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:yelorange"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:red"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:red"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "󰏗"
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:orange"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:peach"
format = '[  $time ]($style)'
