keys:
  - &host_firenation age1mcsg5w5vpm5wua80gzrm5umsq86gn8duj6xeynetw5pnlsk4gcgsrtfq35
  - &host_earthkingdom age1t3az6k9yz7wq2hjat6tn2azwqfferucrmt7ss99wf8j779rswy6q7efcmc
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age: 
        - *host_firenation
        - *host_earthkingdom