# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](name)\
$os\
$username\
[](fg:name bg:host)\
$hostname\
[](fg:host bg:dir)\
$directory\
[](fg:dir bg:git)\
$git_branch\
$git_status\
[](fg:git bg:langs)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$kotlin\
$julia\
$nodejs\
$nim\
$package\
$python\
$rust\
$scala\
[](fg:langs bg:dockerctx)\
$docker_context\
[ ](fg:dockerctx)\
"""

right_format = """
[](time)\
$time\
[](time)\
"""

palette = 'earthkingdom'

[palettes.earthkingdom]

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:name"
style_root = "bg:name"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:host"
ssh_symbol = "󰒋"
format = "[ $ssh_symbol $hostname ]($style)"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:name"
disabled = false # Disabled by default

[os.symbols]
Android = " "
NixOS = " "

[directory]
style = "bg:dir"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:yellangs"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:git"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:git"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:orangyellangse"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "󰏗"
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:langs"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:time"
format = '[  $time ]($style)'
